### ISSUE TITLE
Some questions on this implementation

### ISSUE THREAD

**Issue by tyshiwo** [leehomyc/Photo-Realistic-Super-Resoluton#1]
Hi,

This paper is interesting. Thanks for your implementation!

I mainly have two questions. In line 28 of your adversarial_G.lua file, your wrote:
"nn.Sequential():add(nn.ConcatTable():add(netG):add(nn.Identity())):add(nn.CAddTable(true))".

I'm wondering where is the netG? Is this line a mistake?

BTW, in the original paper, there's no relu function for the second conv in each residual block. In your implementation, it seems you add relu for each second conv in residual blocks.

**Comment by leehomyc** [comment]
Thanks for pointing out the mistakes. I already fixed these two issues in the code.

**Comment by anthonyyuan** [comment]
Can u tell me how to run it 
your_save_folder th run_sr.lua 
{
  ntrain : inf
  beta1 : 0.9
  name : "super_resolution"
  dataset : "folder"
  niter : 250
  lr : 0.001
  model_folder : "your_save_folder"
  batchSize : 32
  scale : 4
  nThreads : 4
  gpu : 1
  train_folder : "your_root_folder"
  loadSize : 96
}
Starting donkey with id: 1 seed: 1
table: 0x09e0bfc0
Starting donkey with id: 3 seed: 3
table: 0x09e2d268
Starting donkey with id: 2 seed: 2
table: 0x09e6c5c0
Starting donkey with id: 4 seed: 4
table: 0x09e4cc10
/Users/anthonyyuan/torch/install/bin/luajit: ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...tic-Super-Resoluton-master/data/donkey_folder_supres.lua:20: bad argument #2 to 'error' (number expected, got string)
stack traceback:
    [C]: in function 'error'
    ...tic-Super-Resoluton-master/data/donkey_folder_supres.lua:20: in main chunk
    [C]: in function 'dofile'
    ...ccc/Photo-Realistic-Super-Resoluton-master/data/data.lua:37: in function <...ccc/Photo-Realistic-Super-Resoluton-master/data/data.lua:27>
    [C]: in function 'xpcall'
    ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
    ...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:41>
    [C]: in function 'pcall'
    ...nthonyyuan/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
    [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
    [C]: in function 'error'
    ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
    ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
    ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
    ...honyyuan/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
    ...ccc/Photo-Realistic-Super-Resoluton-master/data/data.lua:25: in function 'new'
    run_sr.lua:32: in main chunk
    [C]: in function 'dofile'
    ...yuan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x01092b6bc0
yuanhuaans-MacBook-Pro:Photo-Realistic-Super-Resoluto

**Comment by leehomyc** [comment]
Hi Thanks for your interest in the code. 

This means you didn't specify your training folder or your training folder doesnt exist. You should run using the following command:

train_folder=your_root_folder model_folder=your_save_folder th run_sr.lua 

your_root_folder should contain sub-folders that have images in it. A good example is the ImageNet training folder which has 1,000 subfolders and each folder contains images.

I also made a modification on the error handling so now it will tell you explicitly that the training folder does not exist.
